# Rewrite .npz parameters into vars in .py

so we can use it in Android Studio.

In [1]:
import numpy as np

In [2]:
tmp = np.load("vggish_pca_params.npz")

In [3]:
print(tmp.files)

['pca_means', 'pca_eigen_vectors']


In [5]:
len(tmp['pca_means'])

128

In [9]:
len(tmp['pca_eigen_vectors'][0])

128

In [13]:
f = open("vggish_pca_params.py", "w")

f.write("pca_means = [")
cnt = 0
for i in tmp['pca_means']:
    if cnt == 0:
        f.write(str(i))
    else:
        f.write(',' + str(i))
    cnt += 1
f.write(']\n\n')
print(cnt)


128


In [ ]:
f.write("pca_eigen_vectors = [")
cnt1 = 0
for i in tmp['pca_eigen_vectors']:
    if cnt1 != 0:
        f.write(',')
    cnt2 = 0
    for j in i:
        if cnt2 == 0:
            f.write('[' + str(j))
        else:
            f.write(',' + str(j))
        cnt2 += 1
    f.write(']')
    print(cnt2)
    cnt1 += 1
f.write(']\n\n')
print(cnt)
f.close()

# Convert VGGish slim model into .tflite model

so we can use it in Android Studio.

In [32]:
# vggish_slim.py

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import tf_slim as slim

import vggish_params as params


def define_vggish_slim(training=False):
  """Defines the VGGish TensorFlow model.

  All ops are created in the current default graph, under the scope 'vggish/'.

  The input is a placeholder named 'vggish/input_features' of type float32 and
  shape [batch_size, num_frames, num_bands] where batch_size is variable and
  num_frames and num_bands are constants, and [num_frames, num_bands] represents
  a log-mel-scale spectrogram patch covering num_bands frequency bands and
  num_frames time frames (where each frame step is usually 10ms). This is
  produced by computing the stabilized log(mel-spectrogram + params.LOG_OFFSET).
  The output is an op named 'vggish/embedding' which produces the activations of
  a 128-D embedding layer, which is usually the penultimate layer when used as
  part of a full model with a final classifier layer.

  Args:
    training: If true, all parameters are marked trainable.

  Returns:
    The op 'vggish/embeddings'.
  """
  # Defaults:
  # - All weights are initialized to N(0, INIT_STDDEV).
  # - All biases are initialized to 0.
  # - All activations are ReLU.
  # - All convolutions are 3x3 with stride 1 and SAME padding.
  # - All max-pools are 2x2 with stride 2 and SAME padding.
  with slim.arg_scope([slim.conv2d, slim.fully_connected],
                      weights_initializer=tf.truncated_normal_initializer(
                          stddev=params.INIT_STDDEV),
                      biases_initializer=tf.zeros_initializer(),
                      activation_fn=tf.nn.relu,
                      trainable=training), \
       slim.arg_scope([slim.conv2d],
                      kernel_size=[3, 3], stride=1, padding='SAME'), \
       slim.arg_scope([slim.max_pool2d],
                      kernel_size=[2, 2], stride=2, padding='SAME'), \
       tf.variable_scope('vggish'):
    # Input: a batch of 2-D log-mel-spectrogram patches.
    features = tf.placeholder(
        tf.float32, shape=(None, params.NUM_FRAMES, params.NUM_BANDS),
        name='input_features')
    # Reshape to 4-D so that we can convolve a batch with conv2d().
    net = tf.reshape(features, [-1, params.NUM_FRAMES, params.NUM_BANDS, 1])

    # The VGG stack of alternating convolutions and max-pools.
    net = slim.conv2d(net, 64, scope='conv1')
    net = slim.max_pool2d(net, scope='pool1')
    net = slim.conv2d(net, 128, scope='conv2')
    net = slim.max_pool2d(net, scope='pool2')
    net = slim.repeat(net, 2, slim.conv2d, 256, scope='conv3')
    net = slim.max_pool2d(net, scope='pool3')
    net = slim.repeat(net, 2, slim.conv2d, 512, scope='conv4')
    net = slim.max_pool2d(net, scope='pool4')

    # Flatten before entering fully-connected layers
    net = slim.flatten(net)
    net = slim.repeat(net, 2, slim.fully_connected, 4096, scope='fc1')
    # The embedding layer.
    net = slim.fully_connected(net, params.EMBEDDING_SIZE, scope='fc2')
    return tf.identity(net, name='embedding')


def load_vggish_slim_checkpoint(session, checkpoint_path):
  """Loads a pre-trained VGGish-compatible checkpoint.

  This function can be used as an initialization function (referred to as
  init_fn in TensorFlow documentation) which is called in a Session after
  initializating all variables. When used as an init_fn, this will load
  a pre-trained checkpoint that is compatible with the VGGish model
  definition. Only variables defined by VGGish will be loaded.

  Args:
    session: an active TensorFlow session.
    checkpoint_path: path to a file containing a checkpoint that is
      compatible with the VGGish model definition.
  """
  # Get the list of names of all VGGish variables that exist in
  # the checkpoint (i.e., all inference-mode VGGish variables).
  with tf.Graph().as_default():
    define_vggish_slim(training=False)
    vggish_var_names = [v.name for v in tf.global_variables()]

  # Get the list of all currently existing variables that match
  # the list of variable names we just computed.
  vggish_vars = [v for v in tf.global_variables() if v.name in vggish_var_names]

  # Use a Saver to restore just the variables selected above.
  saver = tf.train.Saver(vggish_vars, name='vggish_load_pretrained',
                         write_version=1)
  saver.restore(session, checkpoint_path)


In [33]:
from __future__ import print_function

import numpy as np
import six
import soundfile
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import vggish_input
import vggish_params
import vggish_postprocess

ckpt = 'vggish_model.ckpt'
examples_batch = vggish_input.wavfile_to_examples('test.wav')
pproc = vggish_postprocess.Postprocessor()

with tf.Graph().as_default(), tf.Session() as sess:
    # Define the model in inference mode, load the checkpoint, and
    # locate input and output tensors.
    vggish_slim.define_vggish_slim(training=False)
    vggish_slim.load_vggish_slim_checkpoint(sess, ckpt)
    features_tensor = sess.graph.get_tensor_by_name(
        vggish_params.INPUT_TENSOR_NAME)
    embedding_tensor = sess.graph.get_tensor_by_name(
        vggish_params.OUTPUT_TENSOR_NAME)

    # Run inference and postprocessing.
    [embedding_batch] = sess.run([embedding_tensor],
                                 feed_dict={features_tensor: examples_batch})
    postprocessed_batch = pproc.postprocess(embedding_batch)
    converter = tf.lite.TFLiteConverter.from_session(sess, [features_tensor], [embedding_tensor])
    tflite_model = converter.convert()
    open("saved_model/vggish_feature_extraction_model.tflite", "wb").write(tflite_model)

Jerry vggish_input.py: start wavfile_to_examples()
44100
[[789 789]
 [507 507]
 [154 154]
 ...
 [  0   0]
 [  0   0]
 [  0   0]]
(432488, 2)
Jerry vggish_input.py: start waveform_to_examples()
Jerry vggish_input.py: before resample
after resample
(156912,)
Jerry vggish_input.py: before log_mel
Jerry vggish_input.py: after log_mel
Jerry vggish_input.py: finish waveform_to_examples()
(10, 96, 64)
INFO:tensorflow:Restoring parameters from vggish_model.ckpt


INFO:tensorflow:Restoring parameters from vggish_model.ckpt


In [44]:
embedding_batch.shape

(10, 128)

In [34]:
# The original, "should be", output after post-process
postprocessed_batch

array([[151,  26, 146, ..., 102, 197, 255],
       [154,  26, 168, ...,   0, 138, 255],
       [155,  25, 164, ...,  79, 131, 255],
       ...,
       [175,   8, 146, ..., 147,  69, 255],
       [175,   8, 146, ..., 147,  69, 255],
       [175,   8, 146, ..., 147,  69, 255]], dtype=uint8)

In [ ]:
sample_input = examples_batch[0]
str_input = "{{"
for lst in sample_input:
    str_input += "{" + str(round(lst[0],4)) + "f"
    for num in lst[1:]:
        str_input += "," + str(round(num, 4))+ "f"
    str_input += "},"
str_input = str_input[:-1]
str_input += "}}"
print(str_input)

In [26]:
# Test .tflite model
# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="saved_model/vggish_feature_extraction_model.tflite")
interpreter.allocate_tensors()
# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array([examples_batch[0]], dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

[[0.         0.51773083 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.6152872  0.         0.10851269 0.
  0.         0.11004636 0.         0.         0.06447921 0.
  0.         0.         0.02334112 0.36665872 0.15915178 0.
  0.         0.         0.         0.38003775 0.11620829 0.31883034
  0.         0.         0.         1.068456   0.35640162 0.
  0.         0.         0.8330307  0.         0.         0.
  0.         0.90416443 0.         0.19184536 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.3652949  0.
  0.         1.1452391  0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.24345502
  0.32170972 0.         0.         0.05670428 0.         0.
  0.         0.6894784  0.         0.13961355 0.2678038  0.
  0.         0.24759701 0.         1.3265727  0.         0.94142413
  0.         0. 

In [27]:
pproc.postprocess(output_data)

array([[151,  26, 146,  46, 253,  83, 140,  92, 141, 210, 144,  80, 140,
        234, 173, 102,  48, 181, 129, 147,  29, 211,  90, 111, 124, 164,
        220, 187,  41,  23, 126, 152, 141, 103,  52, 141, 160,  57,  76,
        184, 115,  97,   0, 200,   0, 101,  65, 152, 112, 255, 255,  43,
         93, 147, 144, 149, 113,   0, 110, 195, 222,  48,  22, 255, 166,
        146, 119, 156, 113,   0, 241, 101, 255, 128, 138, 128,  99, 203,
        158, 232,  11, 246, 184, 140, 175, 128, 255, 198,  94,  92,   0,
        255, 203, 187,  79, 200,   0,   0, 255, 147, 255,   0, 225,  59,
          0, 255, 182, 135,   0, 236, 230, 239,   0,  83, 145,   0, 126,
         81,   0, 150,  62,   8,   0, 146, 197, 102, 197, 255]],
      dtype=uint8)

# Helper test for turning python into java

In [120]:
import vggish_pca_params

In [131]:
java_pca_params = ""
pca_params = vggish_pca_params.pca_eigen_vectors
for row in range(len(pca_params)):
    if row == 0: java_pca_params += "{"
    for col in range(len(pca_params[0])):
        if col == 0: java_pca_params += "{" + str(round(pca_params[row][col],3)) + "f"
        else: java_pca_params += "," + str(round(pca_params[row][col],3)) + "f"
    java_pca_params += "},"
java_pca_params = java_pca_params[:-1]
java_pca_params += "}"

In [142]:
f = open("pca_params.txt", "w")
pca_params = vggish_pca_params.pca_eigen_vectors
for row in range(len(pca_params)):
    tmp = ""
    for col in range(len(pca_params[0])):
        tmp += str(round(pca_params[row][col],4)) + " "
    tmp = tmp[:-1]
    f.write(tmp + '\n')
f.close()

In [133]:
java_pca_means = ""
pca_means = vggish_pca_params.pca_means
for row in range(len(pca_means)):
    if row == 0: java_pca_means += "{" + str(round(pca_means[row],3)) + "f"
    else: java_pca_means += "," + str(round(pca_means[row],3)) + "f"
java_pca_means += "}"

In [125]:
np.array(vggish_pca_params.pca_means).shape

(128,)

In [1]:
import vggish_input
wav_file = "testAndroid.wav"
wav_data, sr = vggish_input.wav_read(wav_file)
samples = wav_data / 32768.0

16000
[0 0 0 ... 0 0 0]


In [108]:
from __future__ import print_function

import numpy as np
import six
import soundfile
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import vggish_input
import vggish_params
import vggish_postprocess
import vggish_slim

ckpt = 'vggish_model.ckpt'
examples_batch = wavfile_to_examples(wav_file)

with tf.Graph().as_default(), tf.Session() as sess:
    # Define the model in inference mode, load the checkpoint, and
    # locate input and output tensors.
    vggish_slim.define_vggish_slim(training=False)
    vggish_slim.load_vggish_slim_checkpoint(sess, ckpt)
    features_tensor = sess.graph.get_tensor_by_name(
        vggish_params.INPUT_TENSOR_NAME)
    embedding_tensor = sess.graph.get_tensor_by_name(
        vggish_params.OUTPUT_TENSOR_NAME)

    # Run inference and postprocessing.
    [embedding_batch] = sess.run([embedding_tensor],
                                 feed_dict={features_tensor: examples_batch})

(144384,)
(900, 400) (1280, 8) (8,)
(900, 64)
Jerry vggish_input.py: after log_mel
(900, 64)
(9, 96, 64) (49152, 512, 8) (512, 8)
[-0.64911719 -0.99373337 -1.11742381 -1.86308318 -0.59003545 -0.65416385
 -0.92818919 -0.84284912 -0.67529392 -0.68415773 -0.65729432 -0.23873038
 -1.46176886 -1.97142439 -1.63991142 -0.9172873  -1.38036916 -0.97007554
 -0.2118656  -0.09409409 -0.79908456 -0.17281086 -0.09118928 -0.1033546
 -0.44792192 -0.2422394  -0.31599703 -0.89422089 -0.85059551 -0.75505449
 -0.8879782  -1.7242641  -1.88431059 -1.4866908  -2.05265099 -1.80107311
 -1.78053936 -1.22180689 -0.7424679  -0.28415715 -0.13771165 -1.04611155
 -0.89409162 -0.69065936 -0.95292212 -1.23092642 -1.31773928 -0.82307479
 -0.82023966 -0.12395253  0.08214572 -1.22342371 -2.23763686 -3.17392484
 -3.42293656 -3.35260759 -3.3549805  -3.3102569  -3.18922033 -3.35324471
 -3.20125546 -2.97750483 -3.22362024 -3.49459519]
Instructions for updating:
Please use `layer.__call__` method instead.
Instructions for upd

In [167]:
def postprocess(embeddings_batch):
  """Applies postprocessing to a batch of embeddings.

  Args:
    embeddings_batch: An nparray of shape [batch_size, embedding_size]
      containing output from the embedding layer of VGGish.

  Returns:
    An nparray of the same shape as the input but of type uint8,
    containing the PCA-transformed and quantized version of the input.
  """
  pca_matrix = np.array(vggish_pca_params.pca_eigen_vectors)
  pca_means = np.array(vggish_pca_params.pca_means).reshape(-1, 1)

  pca_applied = np.dot(pca_matrix,
                       (embeddings_batch.T - pca_means)).T

  # Quantize by:
  # - clipping to [min, max] range
  clipped_embeddings = np.clip(
      pca_applied, vggish_params.QUANTIZE_MIN_VAL,
      vggish_params.QUANTIZE_MAX_VAL)

  # - convert to 8-bit in range [0.0, 255.0]
  quantized_embeddings = (
      (clipped_embeddings - vggish_params.QUANTIZE_MIN_VAL) *
      (255.0 /
       (vggish_params.QUANTIZE_MAX_VAL - vggish_params.QUANTIZE_MIN_VAL)))

  # - cast 8-bit float to uint8
  quantized_embeddings = quantized_embeddings.astype(np.uint8)
  quantized_embeddings = np.asarray(quantized_embeddings, order='C')


  print(quantized_embeddings.shape)
  print(quantized_embeddings[0])
  return quantized_embeddings


In [168]:
postprocess(embedding_batch)

(9, 128)
[154  17 141  77 235  73  94 100 125 215 177  60 140 152 158  47  54  89
 157 174  53 223  84 155 119 125 255 163  98 111 149 141 108 165  86  98
 136  91  52  80 134 242 112 249 150 133 119  96  88 118 135  51 115  53
  97  32 158  45  75 179 188   0  40 255 116 132 122  46 191  97 141 151
 185 176  80 115 164 210 115 130  61 157 255  23   3 149 153 146 114  20
  60 138  79 255  33 224  69 111 130 168 255  40 230 167  96 255 170 184
  48 245 238  14  70  78 191   0 176 171  21  50 146   0   0 188 255 113
  99 255]


array([[154,  17, 141, ..., 113,  99, 255],
       [156,  16, 140, ...,  33, 198, 255],
       [155,  19, 144, ...,  96, 255, 255],
       ...,
       [156,  14, 197, ...,  78,  48, 255],
       [155,  17, 191, ...,  33,   0, 255],
       [160,  19, 193, ...,  29,   0, 255]], dtype=uint8)

In [149]:
embedding_batch.T[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08134058, 0.        , 0.        ], dtype=float32)

In [158]:
(embedding_batch.T - np.array(pca_means).reshape(-1,1))[2]

array([-0.12693973, -0.09922631, -0.1271704 ,  0.02063768, -0.1271704 ,
        0.01326802,  0.35762994,  0.46452944,  0.3701476 ])